export const ADDED_SERVICE = 'ADDED_SERVICE';
export const APPROVED_SERVICE = 'APPROVED_SERVICE';
export const EDITED_SERVICE = 'APPROVED_SERVICE';
export const FETCHED_SERVICES = 'FETCHED_SERVICES';
export const FETCHED_PENDING_SERVICES = 'FETCHED_PENDING_SERVICES';
export const SELECTED_SERVICE = 'SELECTED_SERVICE';


